### ISSUE TITLE
Next BeerJS: MON, January 19th@ 6:00pm

### ISSUE THREAD

**Issue by jordanpapaleo** [beerjs/tahoe#14]
We are moving to Mondays to accommodate my new job.  Presenters?

**Comment by jordanpapaleo** [comment]
I will be doing a demo on the new benchmark tool I am working on for Famo.us or you will have to wait until next week and watch my [demo](https://famo.us/blog/).  Drop by for some free beer from Fifty Fifty Brewing and some good discussion on JavaScript.  Remember its Monday NOT Wednesday.﻿

**Comment by jlevine22** [comment]
I can present about Promises (finally)!

**Comment by jordanpapaleo** [comment]
Thanks Josh.

**Comment by gwmccull** [comment]
That'll be awesome Josh.
Thanks,G 

     On Sunday, January 18, 2015 1:16 PM, Josh Levine <notifications@github.com> wrote:
   

 I can present about Promises (finally)!—
