### ISSUE TITLE
Next BeerJS: MON, April 20th@ 6:00pm

### ISSUE THREAD

**Issue by jordanpapaleo** [beerjs/tahoe#18]
Collin Lorentz is going to do a demo that is going to be out of this world (Space Apps).  

If there is time I will do a Famo.us demo but only if there is time as the code required to work with this version of famo.us is not public yet.

Anyone else have something to talk about, demo, or share?

**Comment by jlevine22** [comment]
I'd love to talk about building apps with React Native. Given the topic of Collin's demo it seems appropriate then that the first React Native app I built is an APOD viewer that I'd love to show: https://github.com/jlevine22/apod-react-native

I'm not 100% sure yet that I can make the next meeting though

**Comment by gwmccull** [comment]
A presentation on React Native would be great. 

Colin will be talking about using the voice recognition api in his NASA app. 

G

**Comment by jlevine22** [comment]
I'll be at the meeting and I'm ready to present about React Native!

**Comment by gwmccull** [comment]
That's great. Thanks Josh!

**Comment by jordanpapaleo** [comment]
I will have a few famo.us demos ready it we have extra time
