### ISSUE TITLE
BeerJS - MON May 18th

### ISSUE THREAD

**Issue by gwmccull** [beerjs/tahoe#19]
Christopher will be talking about ES6.

**Comment by HMUDesign** [comment]
I gave a talk at /dev/reno last night on ES6 and am offering to give the same talk to y'all. I broke it up into different features and allowed it be audience directed. It lasted about an hour and didn't cover all the topics I had prepared. It could be anywhere from 10 minutes to 2 hours, as you need.

My repo is available at https://github.com/HMUDesign/talk-es6 if anybody wants to preview it. If you would like the talk, but want me to add a topic to the list, please let me know, too. =]

**Comment by HMUDesign** [comment]
I also saw on #2 that there was a request for both [NW.js](https://github.com/nwjs/nw.js/) (previously known as node-webkit) and [Koa](https://github.com/koajs/koa). I have experience with both of these if you'd like me to give a talk on one of them. Or all of them.

**Comment by HMUDesign** [comment]
I also did a talk a while back at /dev/reno on [three.js](http://threejs.org/) that I could give as well. That repo is at https://github.com/HMUDesign/threejs-talk

**Comment by jordanpapaleo** [comment]
That would be great.

**Comment by gwmccull** [comment]
Christopher's ES6 repo
https://github.com/HMUDesign/talk-es6
