### ISSUE TITLE
Topic Hitlist

### ISSUE THREAD

**Issue by jordanpapaleo** [beerjs/tahoe#2]
# What would you like to see at BeerJS:Tahoe?
## Current Topic Ideas (alpha sort):
- Algorithms
- Application Architecture
- Code Quality
- **Cool Stuff**
- Data Structures
- Electron
- Emerging JavaScript
- Functional JavaScript
- Isomorphic/Universal JavaScript
- Node
- React
- Redux
- RelayJS
- Test Driven Development
- Webpack
- Webpack
- Gulp
- git
- bash scripts
- linting
- transpiling code
- running tests
- semver stuff
- etc
## Node and the IoT

Thoughts?

**Comment by jlevine22** [comment]
React Native

**Comment by CodeTahoe** [comment]
Web Components
