### ISSUE TITLE
BeerJS - MON July 20th

### ISSUE THREAD

**Issue by gwmccull** [beerjs/tahoe#21]

**Comment by gwmccull** [comment]
I'll be attending AngularU and learning about Angular 2.  I'm interested in doing a talk on Angular 2 for the group.  Firebase as offered to give us swag if someone does a Firebase talk.  If no one wants to take that on, I can incorporate that into an NG2 presentation so that @jordanpapaleo can get a new, free t-shirt :-)

What do you think?

**Comment by jordanpapaleo** [comment]
I’d love to hear about what you learn and I think you should incorporate Firebase into it so I can get a new t-shirt.  Remember all the swag I got you from ng-conf ;)
