### ISSUE TITLE
 BeerJS - MON Sept 21st 

### ISSUE THREAD

**Issue by gwmccull** [beerjs/tahoe#23]

**Comment by gwmccull** [comment]
Jordan has offered to do a presentation on ReactJS and D3.

Anyone else want to present?

**Comment by jordanpapaleo** [comment]
Probably just react

Sent from my iPhone

On Aug 31, 2015, at 5:18 PM, Garrett McCullough <notifications@github.com> wrote:

Jordan has offered to do a presentation on ReactJS and D3.

Anyone else want to present?

**Comment by jordanpapaleo** [comment]
Here is the seed project I am using if you want to pull it down and get it running:
https://github.com/jordanpapaleo/web-app

**Comment by jordanpapaleo** [comment]
Also as I am learning ReactJS right now, please be a contributor to this meetup and bring your React knowledge to share.
