### ISSUE TITLE
BeerJS - MON October 19th @ 6:00pm

### ISSUE THREAD

**Issue by jordanpapaleo** [beerjs/tahoe#24]
Presenters?

**Comment by gwmccull** [comment]
Frontend Masters is sponsoring our next event.  Come on by; I've got free yearly memberships to give out.

**Comment by jordanpapaleo** [comment]
I will be continuing the ReactJS Presentation Circuit this month.  We will be discussing life cycle events and how to leverage them.

If anyone else would like to share a topic, pipe up :)

**Comment by jordanpapaleo** [comment]
So i am swamped and will not be able to present this month.  I will be there though.  If someone else wants to let me know.  If no one volunteers we will just hang out and do it more open mic style.

**Comment by gwmccull** [comment]
I've been working on a little Angular project using ES6 classes and the component architecture that Scott Moss advocates as a prep for Ng2. It's nothing spectacular but I can show it off.

Garrett
 


     On Saturday, October 17, 2015 4:41 PM, Jordan Papaleo <notifications@github.com> wrote:
   

 So i am swamped and will not be able to present this month. I will be there though. If someone else wants to let me know. If no one volunteers we will just hang out and do it more open mic style.—
