### ISSUE TITLE
MON November 16th @ 6:00pm

### ISSUE THREAD

**Issue by jordanpapaleo** [beerjs/tahoe#25]
FYI:  Most of my family is out of town.  My 6 year old son will be with me so I will need to have a hard stop at 8.

Anyone want to share?

**Comment by gwmccull** [comment]
Sorry, I'll be out of town for this one.  I still have some Frontend Masters codes that I can give to Jordan to give out.
Garrett
 


     On Monday, November 9, 2015 6:23 PM, Jordan Papaleo <notifications@github.com> wrote:
   

 FYI: Most of my family is out of town. My 6 year old son will be with me so I will need to have a hard stop at 8.Anyone want to share?—

**Comment by typesend** [comment]
If there is interest...  I could do some Elixir show and tell. I am joining the US Digital Service for a few months in DC and could share what that is about. Also, it was recently announced that Filament is deploying a low power IoT network beginning in Reno and I could share some news about how that could be extended and what makes it cool.

**Comment by gwmccull** [comment]
Ah man, all of those sound interesting. Stupid vacation....

**Comment by scaryuncledevin** [comment]
Dang, same night as /dev/Reno,.

**Comment by jordanpapaleo** [comment]
Ok so /dev/reno is the same night.  They moved their event up because of Thanksgiving and they will move theirs up again next month for Christmas.  I am not sure how much overlap in attendance there is in these 2 events.  So I am going to do something I normally don't do; I need some RSVP action here to make sure its even worth doing.  Please comment to this issue if you are attending.  Thanks everyone.

**Comment by peterander** [comment]
Can't make it this month.

**Comment by jack96161** [comment]
Well, /dev/reno is not on my normal agenda - in fact, Monday (or Friday) 
evenings rarely crop up for other events and meetings I do attend 
regularly. Tuesday and Wednesdays seem to be the most popular for 
special interest/government meetings around here.

Moving into the holiday season will generally complicate things anyway. 
Incidentally, pushing for yes/no messages of interest should not rub 
anyone the wrong way - it's just a common courtesy to the organizer (and 
yes, one I forget unless reminded as well...:-( )

Jack Armstrong

of 11/11/2015 1:23 PM, Jordan Papaleo wrote:

**Comment by typesend** [comment]
I can't speak — not enough time to prepare. Probably going to Dev Reno if I go anywhere on Monday.

**Comment by jordanpapaleo** [comment]
There have been 0 confirmations.  This months event will be cancelled.
