### ISSUE TITLE
MON December 21st @ 6:00pm

### ISSUE THREAD

**Issue by jordanpapaleo** [beerjs/tahoe#26]
I know this is Christmas week but we decided to meet anyways because thats what we do.  If we do not have enough people around we will most likely go super informal; more of a show and tell format.  You dont even have to officially volunteer.  Ill just put you on the spot :)

**Comment by CodeTahoe** [comment]
Let's do Web Components w/ Polymer! I can prep a good hours worth of material... come prepared to learn about WC's and why they're the future of web clients everywhere!

**Comment by jack96161** [comment]
If I'm not driving the Zamboni at the regional park ice rink, I'm up for it! 

On December 15, 2015 4:21:24 PM PST, Jordan Papaleo <notifications@github.com> wrote:
>I know this is Christmas week but we decided to meet anyways because
>thats what we do.  If we do not have enough people around we will most
>likely go super informal; more of a show and tell format.  You dont
>even have to officially volunteer.  Ill just put you on the spot :)
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/beerjs/tahoe/issues/26

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gwmccull** [comment]
Sounds great, see you there

**Comment by CodeTahoe** [comment]
I've got a good 2 hours of Web Components lesson,  be prepared to learn and explore! The more people the closer to the two hour mark we'll be, if there are less people it won't take as long to get through certain pieces of the less plan where you'll be broken up into groups.

Cheers!

**Comment by gwmccull** [comment]
Update:  looks like Eric won't be able to make it tonight so instead of Web Components, we'll be talking about D3.js!

**Comment by CodeTahoe** [comment]
Garret & Jordan. Thanks for taking this over... I just can't drive through the hill in my G37 to Truckee tonight. If we could figure out something remote I'd love to still talk
