### ISSUE TITLE
MON January 18th @ 6:00pm

### ISSUE THREAD

**Issue by jordanpapaleo** [beerjs/tahoe#27]
I think we may be in for a presentation from CodeTahoe.

**Comment by CodeTahoe** [comment]
Here's to hoping :+1:

**Comment by spotlmnop** [comment]
Bunch of us are planning to make it tomorrow. Is it still on?

**Comment by gwmccull** [comment]
@spotlmnop Yes, we are still planning to meet tomorrow.  See you then!

**Comment by jordanpapaleo** [comment]
Eric Hodonsky (CEO of Code Tahoe) will be presenting on how to leverage the power of Web Components,  importing HTML Templates, understand the DOM Module,  and use WC Data Binding

**Comment by jordanpapaleo** [comment]
Send over your github account name so Eric can add you to this repo (its private) that he’ll be using if you want to clone it and follow along

**Comment by gwmccull** [comment]
gwmccull

**Comment by typesend** [comment]
typesend

**Comment by tahoeRobbo** [comment]
tahoeRobbo

**Comment by typesend** [comment]
RE: Self closing tags? https://github.com/x-tag/core/issues/47

**Comment by jlevine22** [comment]
jlevine22

**Comment by typesend** [comment]
Thanks for putting this event together you guys! Cheers!

**Comment by gwmccull** [comment]
Great meeting!  Thanks for coming everyone
