### ISSUE TITLE
TUE April 19th @ 6:00pm

### ISSUE THREAD

**Issue by jordanpapaleo** [beerjs/tahoe#30]
We have to move to Tuesdays now that I am teaching classes.  Tuesday will be our new official meeting day.

**Comment by gwmccull** [comment]
Do you want to stick to the 3rd Tuesday?  I think Tuesday works for my schedule.  I think it may conflict with one of the Reno Meetups (maybe the JS one?) and a few of the Reno people attend both.

**Comment by jordanpapaleo** [comment]
If it conflicts no. Let's check that. 

Sent from my iPhone

On Mar 24, 2016, at 10:46 AM, Garrett McCullough <notifications@github.com> wrote:

Do you want to stick to the 3rd Tuesday? I think Tuesday works for my schedule. I think it may conflict with one of the Reno Meetups (maybe the JS one?) and a few of the Reno people attend both.

**Comment by gwmccull** [comment]
RenoJS is on the 2nd Tuesday.  Looks like DevOps Reno is the 3rd Tuesday but I don't our membership really overlaps that group too much so let's give it a try

**Comment by nblasgen** [comment]
I'll be there!

**Comment by jlevine22** [comment]
Gonna  try and make it! What's the topic?

**Comment by gwmccull** [comment]
@nblasgen & @jlevine22, I hope you guys can make it.  We're talking about React Native.  Note that we changed from 3rd Monday to 3rd Tuesday for this month.  Meeting will be Tuesday, April 19

**Comment by nblasgen** [comment]
Any suggestions on a crash course with React / React Native?  We've discussed a lot of React, but I'm still from the Angular side of things and would love to do an introduction to the structure in general before the meeting.  Sadly, doesn't look like CodeSchool has a React course.

**Comment by jordanpapaleo** [comment]
Egghead.io had some good stuff and so does Udemy. The good author on Udemy is named Stephen G.  But the most amazing part of react is using ES2015 JavaScript

Sent from my iPhone

On Apr 17, 2016, at 8:06 PM, nblasgen <notifications@github.com> wrote:

Any suggestions on a crash course with React / React Native? We've discussed a lot of React, but I'm still from the Angular side of things and would love to do an introduction to the structure in general before the meeting. Sadly, doesn't look like CodeSchool has a React course.

**Comment by gwmccull** [comment]
I've been following this tutorial on React:
https://share.viget.com/sxsw/learning-react/lessons/2-jsx/index.html

And going to try this one on React Native next:
https://www.viget.com/articles/learn-you-a-react-native

I also just heard a podcast on the Deco IDE that is supposed to help with writing React.  I heard it's in private beta right now but it may be worth following.

**Comment by gwmccull** [comment]
Here's a link to sign up for the Deco IDE beta:
https://www.decosoftware.com/?r=mg3Rm

It's actually targeted towards React Native programmers right now.

**Comment by gwmccull** [comment]
links:
https://github.com/ptmt/react-native-desktop
https://css-tricks.com/snippets/css/a-guide-to-flexbox/

**Comment by gwmccull** [comment]
Thanks for coming, everyone!
