### ISSUE TITLE
TUE May 17th @ 6:00pm

### ISSUE THREAD

**Issue by gwmccull** [beerjs/tahoe#31]
What topics do we want to discuss?  Josh said he may be able to do a presentation on Webpack.  Anyone else have something?

**Comment by jordanpapaleo** [comment]
Webpack!!! Tooling!!! 

Sent from my iPhone

On Apr 19, 2016, at 10:49 PM, Garrett McCullough <notifications@github.com> wrote:

What topics do we want to discuss? Josh said he may be able to do a presentation on Webpack. Anyone else have something?

**Comment by nblasgen** [comment]
I realize I never found out where to return said borrowed growler from last month.  PM / DM (not sure Github terminology) me

**Comment by jordanpapaleo** [comment]
Send me a text 5307211728 about the growler

**Comment by gwmccull** [comment]
I will also be giving an overview of JavaScript data structures

**Comment by nblasgen** [comment]
Ugh, somehow missed it. Next month...

**Comment by gwmccull** [comment]
Thanks for coming everyone!
