### ISSUE TITLE
TUE June 21st @ 6:00pm

### ISSUE THREAD

**Issue by gwmccull** [beerjs/tahoe#32]

**Comment by gwmccull** [comment]
Who is interested in speaking?

**Comment by jordanpapaleo** [comment]
Ill can about (HapiJS)[http://hapijs.com/].  I feel like we have a webpack presentation past do from a certain person...

**Comment by jordanpapaleo** [comment]
Here is the repo I will be using tonignt: https://github.com/jordanpapaleo/hapi-demo
