### ISSUE TITLE
TUE June 19th @ 6:00pm

### ISSUE THREAD

**Issue by gwmccull** [beerjs/tahoe#33]

**Comment by ertw** [comment]
I'd like to do a quick presentation on functional programming with [Elm](http://elm-lang.org), contrasting with [RamdaJS](http://ramdajs.com), Haskell, F#, and vanilla ES6.  

@gwmccull  Also, I believe this issue title "TUE June 19th" should be replaced with "TUE July 19th".

**Comment by gwmccull** [comment]
@ertw that sounds awesome.  Thanks for volunteering.

**Comment by jordanpapaleo** [comment]
Ahhhhh.  I want cliff notes. 

Sent from my iPhone

On Jul 13, 2016, at 3:56 PM, ertw <notifications@github.com> wrote:

I'd like to do a quick presentation on functional programming with Elm, contrasting with RamdaJS, Haskell, F#, and vanilla ES6.

@gwmccull Also, I believe this issue title "TUE June 19th" should be replaced with "TUE July 19th".
