### ISSUE TITLE
TUE August 16th @ 6:00pm

### ISSUE THREAD

**Issue by jordanpapaleo** [beerjs/tahoe#34]
We got a little behind this month.  Anyone who would like to share will be granted some amazing status with the rest of the world.

Takers?

**Comment by MoonTahoe** [comment]
I may be able to hep. What do you guys want to talk about?

* Emerging JavaScript
* Functional JavaScript
* React
* Redux
* Test Driven React/Redux
* Universal Applications

**Comment by jordanpapaleo** [comment]
Universal Applications, would that be something like Electron?

**Comment by jordanpapaleo** [comment]
Any of these 3 would be great: Emerging JavaScript, Test Driven React/Redux, Universal Applications.

Thanks Alex

**Comment by MoonTahoe** [comment]
Universal, Isomorphic, it means you're not sure weather or not your code is running on the client or the server.

I am going to go over using TDD with react/redux and touch on universal react/redux. We just early released the first 6 chapters of Learning React, so I will be touching on some of the samples and examples found in:

![Learning React Book Cover](https://raw.githubusercontent.com/MoonHighway/learning-react/master/learning-react.jpg)

**Comment by jordanpapaleo** [comment]
FANCY!!!  Will you be bringing signed copies?

**Comment by MoonTahoe** [comment]
Nope it is not in print yet, too many literary bugs!  It is only available online.

I am getting together some file samples for tomorrow. Where do you guys usually keep those? Can I send a pull request?

**Comment by jordanpapaleo** [comment]
Yes.  I just made a directory for demo code in the beers/tahoe repo.  Please put a PR in and Ill get it in asap.

Thanks!

**Comment by jordanpapaleo** [comment]
I would like to chat with everyone about what our next steps are for growing our meet up.  What do we need to do to bring BeerJS:Tahoe to the next level?

**Comment by gwmccull** [comment]
@jordanpapaleo let's start a new issue to talk about how to grow the group

**Comment by nblasgen** [comment]
Can we get https://beerjs-slack-invite.herokuapp.com/ added to the Slack link on the main page as a link next to the Slack channel -- https://github.com/beerjs/tahoe/#the-community

**Comment by gwmccull** [comment]
@nblasgen thanks for the suggestion.  I've added it

**Comment by jordanpapaleo** [comment]
@MoonTahoe Home run last night.  Thanks for sharing with us.  I am going to really put effort into TDD as long as my ADD doesn't ruin it.
