### ISSUE TITLE
TUE September 20th @ 6:00pm

### ISSUE THREAD

**Issue by jordanpapaleo** [beerjs/tahoe#36]
Docker is being postponed until I get my head above water.

We will have a guest presenter who will be discussing the topic career technical education.

Todd Wold recently completed his doctorate in Educational Leadership from U.C. Santa Barbara and Cal Poly San Luis Obispo and relocated here in January, 2016.  

He is the Engineering Technology Pathway coordinating teacher at North Tahoe High School, the Summer STEAM Academy Director, and the Career Technical Education (CTE) Advisory for the district where he oversees the expansion and implementation of industry and post-secondary partnerships with our three high schools and their themed pathways.

He also is a National Faculty Consultant on Project-Based Learning for The Buck Institute for Education.  Here is one of his blogs: http://www.bie.org/blog/pbl_steam_cte_validation_through_triangulation

Lastly, Todd owns Wold Organizational Leadership Development, LLC (www.WOLDLLC.com) and consult on PBL, Learning Organizations, and Professional Learning Communities.  

Please join us for some free beer and good company.

**Comment by jordanpapaleo** [comment]
Getting an early start this time.  Who wants to present?

**Comment by jordanpapaleo** [comment]
Since no one wants the floor, I was thinking about talking about web application tooling if anyone is interested.

**Possible** topics to discuss: 

-Webpack
- Gulp
- git
- bash scripts
- linting
- transpiling code
- running tests
- semver stuff
- etc

Thoughts?

**Comment by jordanpapaleo** [comment]
!!!!! TOPIC CHANGE !!!!!

**Comment by jack96161** [comment]
Hi Jordan,

I'll be there tonight and have invited some folks from TEA (Tahoe 
Expedition Academy) who are interested in on project based learning.

Jack Armstrong

**Comment by jordanpapaleo** [comment]
Awesome!

**Comment by jordanpapaleo** [comment]
twold@ttusd.org

**Comment by jordanpapaleo** [comment]
From Todd:

Can you pass these on to the group?  These are the types of things that I think students would engage in that would get them hooked in to needing to know how to code and use technology in innovative ways.  

The last one is also an example of how coding can apply to something like culinary.

https://www.youtube.com/watch?v=Ki8UXSJmrJE

https://www.youtube.com/watch?v=rjWcE25s7kQ

http://projection-mapping.org/le-petit-chef-projection-mapping-on-your-dinner-plate/
