### ISSUE TITLE
Non Profit

### ISSUE THREAD

**Issue by jordanpapaleo** [beerjs/tahoe#40]
Determine the qualifications to be a non profit organization.  Report findings to the team and lets discuss.

**Comment by gwmccull** [comment]
I know the lawyer that helped Silicon Mountain with a similar question. I'll ask him. He may still be on vacation so it may take a little while

**Comment by jack96161** [comment]
Great. Brent Collison is the attorney that help get the nonprofit status 
for a new flying club at the airport not too long ago. I can ask him is 
you want as well. He's the airport district attorney of record.

**Comment by nblasgen** [comment]
Non-profit status is only useful if you have a goal in mind that cannot be met with the current structure.  Any company is required to pay for a business license and yearly state filing fees.  In California, it's not horrible for a non-profit, but it's still a few hundred per year (compared to $1k/yr for a business).  Are the benefits of the non-profit status that good?  There's also an IRS filing fee if you want to take write-off donations.

While I've never done the paperwork, I'm happy to help.  It's not a horrible process and seems very similar to the process of creating an LLC, just with different boxes to check.

**Comment by jordanpapaleo** [comment]
The benefits would be people that say they would support if this was a non profit.  Right now I have to focus on the funds going to the event.  I have already covered a third of the robot cost myself.

I would like to look into this more once I hopefully pay myself back :)

I would appreciate help as well :)
