### ISSUE TITLE
Investigate a contribution to Kidzone

### ISSUE THREAD

**Issue by jordanpapaleo** [beerjs/tahoe#46]
- What would they be able to comprehend?
- Look into some kid programming topics

**Comment by jack96161** [comment]
I'll take this to the KidZone board - most of our programs are 
pre-school, but we've already had sessions with "squishy circuits" - 
conductive play-dough, batteries, light bulbs, buzzers, etc. We're also 
talking about after-school and weekend sessions for older kids. Somebody 
in Truckee was recently asking for tutors to talk about programming for 
home-schooled kids and there are several schools that would be happy to 
advertise events. Lots of possible venues. I'd like to see some outreach 
to places like the Boys & Girls club in King's Beach, the Family center 
in Truckee - low income kids who have less opportunities for things like 
this...

**Comment by jordanpapaleo** [comment]
Cool. I have thought about that a lot. And the thing I do not know how to figure out is hardware. How do we get these kids computers to use while learning and then how do they keep up on their skills. I need a building and a computer lab. 

Sent from my iPhone

On Aug 18, 2016, at 5:22 PM, jack96161 <notifications@github.com> wrote:

I'll take this to the KidZone board - most of our programs are 
pre-school, but we've already had sessions with "squishy circuits" - 
conductive play-dough, batteries, light bulbs, buzzers, etc. We're also 
talking about after-school and weekend sessions for older kids. Somebody 
in Truckee was recently asking for tutors to talk about programming for 
home-schooled kids and there are several schools that would be happy to 
advertise events. Lots of possible venues. I'd like to see some outreach 
to places like the Boys & Girls club in King's Beach, the Family center 
in Truckee - low income kids who have less opportunities for things like 
this...

**Comment by jack96161** [comment]
Suggestion: for the hardware, let's come up with a list and approach the 
airport for support. For a venue, the Kid Zone has a small crafts room 
thats available but not good for more than maybe 6-8 kids at most. The 
old rec center downtown has rooms used for things like this, and if it's 
not anything messy, the airport terminal building meeting rooms can be 
scheduled. The school district has allowed several after school 
'enrichment' programs to use their facilities. In short, I think the 
venue is a doable - what we need is a program, what it would accomplish, 
and what bits and pieces would be required. These days, the school 
district distributes a ton of Chrome books for school work. If they have 
a browser, we can supply a website, right?

Need to research programming languages and tools for teaching beginning 
(/really /beginning) programming. Many years ago, I taught a class of 
4-5th graders about how a computer works. One kid was the cpu, who sat 
at a desk and got numbers to add and subtract with pencil and paper - 
one kid at the blackboard was the memory who put numbers in numbered 
(addressed) or labelled (named) boxes - another was the input device who 
took cards from a stack of cards (the 'program') with numbers or 
instructions to give to the cpu - and two kids were the wires who ran 
numbers to and fro. Finally, there was a 'printer' who posted the 
answers for the teacher. I think there was an instruction set of maybe 
6-8 things for the cpu to do. I'm a push down stack architecture kid of 
guy, but you could (ugh!) use a brain dead fixed register model like IBM 
inflicted on us. Great way to teach the basic concept of name vs. value 
years before it confuses them in beginning algebra. I'm convinced the 
teacher learned more than the kids. Today, there must be a number of 
very basic languages for programming simple robots, games, you name it. 
Or... we all know how to write an interpretive compiler or two, right?

Climb out of the box and think about it!

Jack

**Comment by sjtaillon** [comment]
You guys probably already know about it, but I love, love, love the code.org
programming activities. The first one uses only graph paper, and then they
get progressively more interesting. They make learning programming concepts
like loops fun with games.

I'd be interested in helping with this project. My hands-on coding skillz
are pretty dated at this point, but I'm pretty decent working with kids and
explaining technical concepts in an easy-to-follow way. I may have some
time on Fridays starting in Sept. Let me know if I can help somehow. What a
great cause!!

Best,
Sara.

**Comment by jack96161** [comment]
Sara - code.org is super! I hadn't heard of it, but you started me off 
on a search for intro to programming for kids - there's a ton of work 
being done in this area. Reached out to some friends and former 
co-workers and found https://scratch.mit.edu/about/ from the MIT Lab, 
http://www.alice.org/index.php, fun stuff and ideas on 
http://lifehacker.com/how-and-why-to-teach-your-kids-to-code-510588878 , 
on and on... Google labs has some projects for this as well.

There are no end of opportunities for people with computer skills to 
teach some fun classes, mentor science projects, work with the local 
school district STEAM programs, etc. The BeerJS folks are massively 
overqualified for this, but I suspect could come up with more than one 
way to improve on these tools and programs using the newer technologies 
that have been kicked around in these earlier meetings.

I'm most interested in how we can harness the current shot-gun approach 
to suggestions and ideas for an interesting expansion of the original 
BeerJS idea (there /was /one, wasn't there?) beyond Javascript and JS 
based platforms and tools. Aiding and abetting kids to try programming 
and creativity is one definable area, can someone outline a handful of 
others to examine more closely?

**Comment by jordanpapaleo** [comment]
Sara! hi!

Lets use the [tahoe channel in beerjs slack](https://beerjs-slack-invite.herokuapp.com/) for our general conversation so we can have better interactions.  We can then record results in the issues :)
