### ISSUE TITLE
BeerJS:Tahoe October 18, 2016

### ISSUE THREAD

**Issue by jordanpapaleo** [beerjs/tahoe#49]
Who wants to share some love?

**Comment by eveporcello** [comment]
I'd love to give a talk about the spread operator that I'm giving at a conference a week later. Maybe 20 mins or so? Thanks!

**Comment by jordanpapaleo** [comment]
Absolutely!

Sent from my iPhone

On Sep 23, 2016, at 2:19 PM, Eve Porcello <notifications@github.com> wrote:

I'd love to give a talk about the spread operator that I'm giving at a conference a week later. Maybe 20 mins or so? Thanks!
