### ISSUE TITLE
BeerJS:Tahoe Mon Jan 17th @ 6pm

### ISSUE THREAD

**Issue by jordanpapaleo** [beerjs/tahoe#52]
Its the first BeerJS of the year; I can think of a better way to kick the year off than by talking about testing your react application.

Come hangout and I'll talk about the 4 month battle I had with react unit testing and where I am now.

Topics: React, Redux, Unit Testing, Jest, Enzyme

**Comment by gwmccull** [comment]
I'll be giving a presentation on how to use Markdown, Jekyll and Pandoc to write your content once, and then use it to create websites, ebooks, presentations, etc

**Comment by gwmccull** [comment]
Here's the repo for tomorrow:  
https://github.com/gwmccull/jekyll-presentation
