### ISSUE TITLE
BeerJS:Tahoe Wed Feb 22nd @ 6pm

### ISSUE THREAD

**Issue by gwmccull** [beerjs/tahoe#53]
Rachel Arst McCullough and Garrett McCullough are speaking at the next TahoeJS meeting about our experience at the Mountain Ventures Summit. 

Mountain Ventures Summit was a conference for people interested in diversifying and growing the economies of small mountain towns.

Come and learn about how you can make a difference!

**Comment by jordanpapaleo** [comment]
BEERJS Cancelled tonight. Rescheduled for tomorrow.

**Comment by gwmccull** [comment]
Updating the issue headline from 2/21 to 2/22
