### ISSUE TITLE
April 18th at 6:00 pm

### ISSUE THREAD

**Issue by jordanpapaleo** [beerjs/tahoe#55]
@beerjs/tahoe 

This week we will be doing some Show and Tell for projects we are working.  Garrett and I both have stuff to share.  I have been working with React, Aframe.io, and the Open Spherical Camera spec.  Garrett has some cool stuff in store and maybe even some cool stuff from Alex Banks on React Router.  Hope to see you there.

https://github.com/jordanpapaleo/beerjs-360-demo

**Comment by gwmccull** [comment]
I can share a few things I've been working on. 

I've also been working on a planning doc to plan a Node School event. I'd like to put that to the group and see who is interested in helping. It should be pretty easy 

G

**Comment by MoonTahoe** [comment]
I spent all week upgrading to the React Router v4.0... If we are looking to fill time I could probably talk about that.

**Comment by gwmccull** [comment]
I spent two+ weeks upgrading from React Native 36 to React Native 42 so I could go on a rant all night long if anyone wants :-)
G
 

    On Thursday, April 6, 2017 11:39 AM, Alex Banks <notifications@github.com> wrote:
 

 I spent all week upgrading to the React Router v4.0... If we are looking to fill time I could probably talk about that.—

**Comment by MoonTahoe** [comment]
HAPPY BIRTHDAY JORDAN!!!

**Comment by jordanpapaleo** [comment]
:)

Thanks!

Sent from my smallest computer

On Apr 21, 2017, at 4:26 PM, Alex Banks <notifications@github.com> wrote:

HAPPY BIRTHDAY JORDAN!!!
