### ISSUE TITLE
July 18th at 6:00 pm

### ISSUE THREAD

**Issue by gwmccull** [beerjs/tahoe#58]
@MoonTahoe, Eve Porcello and I will be talking about lessons learned at Fluent Conf 2017

**Comment by gwmccull** [comment]
here's a link to my slide repo
https://github.com/gwmccull/fluent-conf-presentation

**Comment by gwmccull** [comment]
@MoonTahoe 's mini-app for drawing names from a hat:
https://the-hat.glitch.me/

**Comment by jjulian** [comment]
I just moved to Truckee. Sorry I missed this one, hopefully see you next month!
