### ISSUE TITLE
AUG 15th at 6:00 pm

### ISSUE THREAD

**Issue by gwmccull** [beerjs/tahoe#59]
Special guest, Ava Holliday, will be talking about the importance of diversity, inclusion, and equity in tech. She will give evidence about why these topics are so important for building stronger teams and working towards a fairer society.

**Comment by hekaldama** [comment]
Hey there.

Is it "equity" or "equality"?

Thanks!

**Comment by gwmccull** [comment]
I guess it could be either the first definition of equity or equality.  But we're not talking about stock :-)



<img width="476" alt="screen shot 2017-08-08 at 7 13 31 am" src="https://user-images.githubusercontent.com/580060/29076046-251cb072-7c09-11e7-95d7-51a0633167fe.png">
<img width="575" alt="screen shot 2017-08-08 at 7 14 28 am" src="https://user-images.githubusercontent.com/580060/29076083-4048f540-7c09-11e7-8eed-96cd9e469505.png">

**Comment by hekaldama** [comment]
Ah! TIL.
